Feature/create reports
DCC-CC4401/2020-1-grupo1 pull request #24
Opened 2020-06-02 16:44 UTC by kawallala

# Lógica y vista de subir reportes
## Objetivo
- resuelve #17 y #18 mediante la implementación de un modelo para agregar reportes, y una vista encargada de subir el reporte creado por un usuario

## Implementación
- Se crea el modelo de ```Reporte```. Un ```Reporte``` contiene información del evento a reportar e información del ```User``` que lo crea
- Se implementa una vista para que un ```User``` registrado pueda crear reportes, por ahora el field ```foto``` es requerido

## Como probar
- primero, se debe realizar ```python manage.py migrate``` para actualizar los cambio a la base de datos
- luego, se corre el servidor con ```python manage.py runserver```, se inicia sesión con un usuario registrado, y se crea un reporte
- Para verificar la creación del reporte hay dos rutas

1.  Usar la consola de admin con un superusuario y verificar los modelos creados
1. Usar ```python manage.py shell```, importar el modelo con ```from sosafitosapp.models import Reporte```, y hacer ```Reporte.objects.all()``` para ver los reportes creados

2020-06-21 22:29 UTC, sanguineti requested changes
Debes corregir las migraciones que hay en tu rama con respecto a las que hay en develop. En django, las migraciones solo pueden tener un "padre". (esto se setea en las `dependencies` de cada migración). En particular, `0002_tag.py` ya apuntaba hacia `0001_initial`, ahora `0002_auto_20200615_1914`también lo hace, lo que es un error. Para corregirlo, debe apuntar a `0002_tag`.

2020-06-21 22:39 UTC, kawallala commented
Es verdad, pero Django lo soluciono con la ```0004_merge_20200618_1907.py```, que fusiona las migrations, con eso he tenido 0 problemas en hacer funcionar las cosas.

> Debes corregir las migraciones que hay en tu rama con respecto a las que hay en develop. En django, las migraciones solo pueden tener un "padre". (esto se setea en las `dependencies` de cada migración). En particular, `0002_tag.py` ya apuntaba hacia `0001_initial`, ahora `0002_auto_20200615_1914`también lo hace, lo que es un error. Para corregirlo, debe apuntar a `0002_tag`.

2020-06-21 22:45 UTC, kawallala commented
@sanguineti cambios realizados, funcionando en mi pc

2020-06-21 23:25 UTC, sanguineti commented
> Es verdad, pero Django lo soluciono con la `0004_merge_20200618_1907.py`, que fusiona las migrations, con eso he tenido 0 problemas en hacer funcionar las cosas.
> 
> > Debes corregir las migraciones que hay en tu rama con respecto a las que hay en develop. En django, las migraciones solo pueden tener un "padre". (esto se setea en las `dependencies` de cada migración). En particular, `0002_tag.py` ya apuntaba hacia `0001_initial`, ahora `0002_auto_20200615_1914`también lo hace, lo que es un error. Para corregirlo, debe apuntar a `0002_tag`.

No lo soluciona, de hecho en mi computador no funciona


> @sanguineti cambios realizados, funcionando en mi pc

Gracias. Ahora recibo un `django.db.utils.IntegrityError: NOT NULL constraint failed: new__sosafitosapp_reporte.ciudad`eso sí.

2020-06-22 19:14 UTC, JaramilloCris approved these changes
Puedo crear reportes sin ningun problema ^^ lo que si la api de google map no me deja acceder

2020-06-22 22:25 UTC, Enzo-Miguel approved these changes
La probé y después de instalar los requerimientos no hubo problema con correr la pagina y los reportes se crearon sin problema.

2020-06-22 23:00 UTC, merged